/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo_arboles;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

  

/**
 *
 * @author pablo
 */
public class Interfaz_Arboles extends javax.swing.JFrame {
    String NodoIng, CadenaAr;
    Arbol NuestroArbol = new Arbol();
   
    /**
     * Creates new form Interfaz_Arboles
     */
    public Interfaz_Arboles() {
        initComponents();
    }

     private void guardarDatosEnArchivo(String nombreArchivo) {
        try {
        String rutaArchivo = System.getProperty("user.dir") + "\\" + nombreArchivo;
        System.out.println("Guardando datos en el archivo: " + rutaArchivo);
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaArchivo))) {
            guardarDatosEnOrden(NuestroArbol.raiz, writer);
        }
    } catch (IOException e) {
        System.err.println("Error al guardar los datos en el archivo: " + e.getMessage());
    }
    }

    private void guardarDatosEnOrden(Nodo nodo, BufferedWriter writer) throws IOException {
        if (nodo != null) {
            guardarDatosEnOrden(nodo.getIzquierda(), writer);
            writer.write(nodo.getDato());
            writer.newLine();
            guardarDatosEnOrden(nodo.getDerecha(), writer);
        }
    }
    
    private void cargarDatosDesdeArchivo(String nombreArchivo) {
    try (BufferedReader reader = new BufferedReader(new FileReader(nombreArchivo))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            NuestroArbol.insertar(linea);
        }
    } catch (IOException e) {
        System.err.println("Error al cargar los datos desde el archivo: " + e.getMessage());
    }
}

private void mostrarDatosEnTextArea() {
    StringBuilder sb = new StringBuilder();
    mostrarDatosEnOrden(NuestroArbol.raiz, sb);
    IngresoActualText.setText(sb.toString());
}

private void mostrarDatosEnOrden(Nodo nodo, StringBuilder sb) {
    if (nodo != null) {
        mostrarDatosEnOrden(nodo.getIzquierda(), sb);
        sb.append(nodo.dato).append("\n");
        mostrarDatosEnOrden(nodo.getDerecha(), sb);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ingresar_Text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Ingresar_Btm = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecoridoOrden_Text = new javax.swing.JTextArea();
        IngresoActualText = new javax.swing.JTextField();
        PosOrden_Btm = new javax.swing.JButton();
        InOrden_Btm = new javax.swing.JButton();
        PreOrden_Btm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        Ingresar_Text.setBackground(new java.awt.Color(102, 102, 102));
        Ingresar_Text.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(Ingresar_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 510, 30));

        jButton1.setText("Leer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 80, -1));

        Ingresar_Btm.setText("Ingresar");
        Ingresar_Btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_BtmActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar_Btm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recorido");

        jButton6.setText("Salvar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        RecoridoOrden_Text.setBackground(new java.awt.Color(102, 102, 102));
        RecoridoOrden_Text.setColumns(20);
        RecoridoOrden_Text.setForeground(new java.awt.Color(0, 255, 0));
        RecoridoOrden_Text.setRows(5);
        jScrollPane1.setViewportView(RecoridoOrden_Text);

        IngresoActualText.setBackground(new java.awt.Color(102, 102, 102));
        IngresoActualText.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(157, 157, 157))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(IngresoActualText))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(IngresoActualText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 910, 190));

        PosOrden_Btm.setText("PosOrden");
        PosOrden_Btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosOrden_BtmActionPerformed(evt);
            }
        });
        jPanel1.add(PosOrden_Btm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, -1));

        InOrden_Btm.setText("InOrden");
        InOrden_Btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InOrden_BtmActionPerformed(evt);
            }
        });
        jPanel1.add(InOrden_Btm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 90, -1));

        PreOrden_Btm.setText("PreOrden");
        PreOrden_Btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreOrden_BtmActionPerformed(evt);
            }
        });
        jPanel1.add(PreOrden_Btm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 90, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Orden del arbol");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 190, 30));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 650, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_BtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_BtmActionPerformed
        NodoIng = Ingresar_Text.getText();
        NuestroArbol.insertar(NodoIng);
        
        CadenaAr = CadenaAr + " - " + NodoIng;
        IngresoActualText.setText(CadenaAr);
    }//GEN-LAST:event_Ingresar_BtmActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        guardarDatosEnArchivo("nombre_del_archivo.txt");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuestroArbol.vaciar(); // Eliminar todos los elementos del árbol
        CadenaAr = ""; // Vaciar el String
        
        cargarDatosDesdeArchivo("nombre_del_archivo.txt");
        mostrarDatosEnTextArea();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PreOrden_BtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreOrden_BtmActionPerformed
        RecoridoOrden_Text.setText(NuestroArbol.preorden().toString());
    }//GEN-LAST:event_PreOrden_BtmActionPerformed

    private void InOrden_BtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InOrden_BtmActionPerformed
        RecoridoOrden_Text.setText(NuestroArbol.inorden().toString());
    }//GEN-LAST:event_InOrden_BtmActionPerformed

    private void PosOrden_BtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosOrden_BtmActionPerformed
        RecoridoOrden_Text.setText(NuestroArbol.postorden().toString());
    }//GEN-LAST:event_PosOrden_BtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Arboles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InOrden_Btm;
    private javax.swing.JButton Ingresar_Btm;
    private javax.swing.JTextField Ingresar_Text;
    private javax.swing.JTextField IngresoActualText;
    private javax.swing.JButton PosOrden_Btm;
    private javax.swing.JButton PreOrden_Btm;
    private javax.swing.JTextArea RecoridoOrden_Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

