/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo_arboles;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;


/**
 *
 * @author pablo
 */
public class Interfaz_Arbol2 extends javax.swing.JFrame {

    
    private final Arbol NuestroArbol = new Arbol();
    private String CadenaAr;
    /**
     * Creates new form Interfaz_Arbol2
     */
    public Interfaz_Arbol2() {
        initComponents();
        CadenaAr = "";
    }

    private void cargarDatosDesdeArchivo(String nombreArchivo) {
    try {
        File archivo = new File(nombreArchivo);
        if (!archivo.exists()) {
            archivo.createNewFile();
        }
        
        try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                NuestroArbol.insertar(linea);
            }
        }
    } catch (IOException e) {
        System.err.println("Error al cargar los datos desde el archivo: " + e.getMessage());
    }
}

private void mostrarDatosEnTextArea() {
    StringBuilder sb = new StringBuilder();
    mostrarDatosEnOrden(NuestroArbol.raiz, sb);
    ArbolActualTxT.setText(sb.toString());
}

private void mostrarDatosEnOrden(Nodo nodo, StringBuilder sb) {
    if (nodo != null) {
        mostrarDatosEnOrden(nodo.getIzquierda(), sb);
        sb.append(nodo.dato).append("\n");
        mostrarDatosEnOrden(nodo.getDerecha(), sb);
    }
}

private void guardarDatosEnArchivo(String nombreArchivo) {
    try {
        File archivo = new File(nombreArchivo);
        if (!archivo.exists()) {
            archivo.createNewFile();
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
            guardarDatosEnOrden(NuestroArbol.raiz, writer);
        }
    } catch (IOException e) {
        System.err.println("Error al guardar los datos en el archivo: " + e.getMessage());
    }
}

private void guardarDatosEnOrden(Nodo nodo, BufferedWriter writer) throws IOException {
    if (nodo != null) {
        guardarDatosEnOrden(nodo.getIzquierda(), writer);
        writer.write(nodo.dato);
        writer.newLine();
        guardarDatosEnOrden(nodo.getDerecha(), writer);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GuardarBtm = new javax.swing.JButton();
        ResultadoTxT = new javax.swing.JTextField();
        ArbolActualTxT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IngresarBtm = new javax.swing.JButton();
        LeerBtm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        RecorridoTxT = new javax.swing.JTextField();
        Buscar_TxT = new javax.swing.JTextField();
        Recorrido_TxT = new javax.swing.JTextField();
        EliminarBtm = new javax.swing.JButton();
        EliminarTxT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultado");

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actual");

        GuardarBtm.setBackground(new java.awt.Color(204, 255, 255));
        GuardarBtm.setForeground(new java.awt.Color(0, 0, 0));
        GuardarBtm.setText("Guardar");
        GuardarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtmActionPerformed(evt);
            }
        });

        ResultadoTxT.setBackground(new java.awt.Color(51, 51, 51));
        ResultadoTxT.setForeground(new java.awt.Color(204, 255, 255));

        ArbolActualTxT.setBackground(new java.awt.Color(51, 51, 51));
        ArbolActualTxT.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResultadoTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArbolActualTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuardarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(752, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ResultadoTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(GuardarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArbolActualTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 454, 849, -1));

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, 93, 35));

        IngresarBtm.setBackground(new java.awt.Color(204, 255, 204));
        IngresarBtm.setForeground(new java.awt.Color(0, 0, 0));
        IngresarBtm.setText("Ingresar");
        IngresarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBtmActionPerformed(evt);
            }
        });
        jPanel1.add(IngresarBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        LeerBtm.setBackground(new java.awt.Color(204, 255, 204));
        LeerBtm.setForeground(new java.awt.Color(0, 0, 0));
        LeerBtm.setText("Leer");
        LeerBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerBtmActionPerformed(evt);
            }
        });
        jPanel1.add(LeerBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 70, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("PosOrden");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 90, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("InOrden");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 90, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("PreOrden");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 90, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 80, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Recorrido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        RecorridoTxT.setBackground(new java.awt.Color(51, 51, 51));
        RecorridoTxT.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(RecorridoTxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 24, 510, 30));

        Buscar_TxT.setBackground(new java.awt.Color(51, 51, 51));
        Buscar_TxT.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Buscar_TxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 160, -1));

        Recorrido_TxT.setBackground(new java.awt.Color(51, 51, 51));
        Recorrido_TxT.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Recorrido_TxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 160, -1));

        EliminarBtm.setBackground(new java.awt.Color(255, 204, 255));
        EliminarBtm.setForeground(new java.awt.Color(0, 0, 0));
        EliminarBtm.setText("Eliminar");
        EliminarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtmActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        EliminarTxT.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(EliminarTxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 160, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Ordenes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 170, 20));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 70));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 200, 180));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 200, 210));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtmActionPerformed
        guardarDatosEnArchivo("nombre_del_archivo.txt");
    }//GEN-LAST:event_GuardarBtmActionPerformed

    private void IngresarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBtmActionPerformed
        String NodoIng = RecorridoTxT.getText();
        NuestroArbol.insertar(NodoIng);

        CadenaAr += NodoIng + " - ";
        ResultadoTxT.setText(CadenaAr);
        
        NuestroArbol.graficar("arbol_numeros.jpg");
    }//GEN-LAST:event_IngresarBtmActionPerformed

    private void LeerBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerBtmActionPerformed
        NuestroArbol.vaciar(); // Eliminar todos los elementos del árbol
        CadenaAr = ""; // Vaciar el StringBuilder

        cargarDatosDesdeArchivo("nombre_del_archivo.txt");
        mostrarDatosEnTextArea();
        NuestroArbol.graficar("arbol_numeros.jpg");
    }//GEN-LAST:event_LeerBtmActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String NodoBuscar = Buscar_TxT.getText();    
        Recorrido_TxT.setText(NuestroArbol.buscar(NodoBuscar));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EliminarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtmActionPerformed
        NuestroArbol.borrar(EliminarTxT.getText());
 
        NuestroArbol.graficar("arbol_numeros.jpg");
    }//GEN-LAST:event_EliminarBtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Arbol2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Arbol2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArbolActualTxT;
    private javax.swing.JTextField Buscar_TxT;
    private javax.swing.JButton EliminarBtm;
    private javax.swing.JTextField EliminarTxT;
    private javax.swing.JButton GuardarBtm;
    private javax.swing.JButton IngresarBtm;
    private javax.swing.JButton LeerBtm;
    private javax.swing.JTextField RecorridoTxT;
    private javax.swing.JTextField Recorrido_TxT;
    private javax.swing.JTextField ResultadoTxT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
